export const KEYWORD_LIBRARY: Record<string, string[]> = {
  "Beauty / Skincare": [
    "cerave", "the ordinary", "drunk elephant", "tatcha", "glow recipe",
    "glossier", "rare beauty", "rhode skin", "summer fridays", "sol de janeiro",
    "olaplex", "k18", "bondi sands", "supergoop", "paula's choice",
    "innisfree", "laneige", "cosrx", "beauty of joseon", "anua",
    "tower 28", "ilia beauty", "merit beauty", "saie", "kosas",
    "fenty beauty", "charlotte tilbury", "nars", "mac cosmetics", "too faced",
    "benefit cosmetics", "urban decay", "tarte", "nyx cosmetics", "maybelline",
    "l'oreal", "neutrogena", "cetaphil", "la roche-posay", "bioderma",
    "glass skin", "slugging", "skin barrier", "skin cycling", "retinol",
    "hyaluronic acid", "niacinamide", "vitamin c serum", "salicylic acid", "benzoyl peroxide",
    "double cleansing", "oil cleansing", "snail mucin", "peptide serum", "bakuchiol",
    "sunscreen reapplication", "tinted sunscreen", "mineral sunscreen", "chemical exfoliant", "aha bha",
    "lip gloss", "lip oil", "lip liner hack", "blush placement", "contour tutorial",
    "concealer hack", "foundation shade match", "setting spray", "beauty blender", "makeup brush set",
    "skincare routine", "morning routine skincare", "nighttime skincare", "skincare fridge", "ice roller",
    "gua sha", "jade roller", "face mask", "sheet mask", "peel off mask",
    "dermaplaning", "microneedling", "led face mask", "facial steamer", "pore strips",
    "acne patches", "pimple patches", "hydrocolloid patches", "spot treatment", "dark spot corrector",
    "under eye patches", "eye cream", "lip mask", "lip scrub", "body butter",
    "body oil", "fake tan", "self tanner", "gradual tan", "body lotion",
    "hair oil", "hair mask", "leave in conditioner", "heat protectant", "dry shampoo",
    "scalp scrub", "scalp serum", "hair growth serum", "rosemary oil hair", "rice water hair",
    "perfume dupe", "fragrance layering", "body mist", "vanilla perfume", "clean girl aesthetic"
  ],
  "Fashion / Apparel": [
    "lululemon", "nike", "adidas", "new balance", "asics",
    "on running", "hoka", "birkenstock", "ugg", "crocs",
    "zara", "h&m", "uniqlo", "cos", "arket",
    "aritzia", "abercrombie", "free people", "anthropologie", "madewell",
    "everlane", "reformation", "realisation par", "skims", "alo yoga",
    "vuori", "gymshark", "fabletics", "beyond yoga", "girlfriend collective",
    "doc martens", "converse", "vans", "golden goose", "vejas",
    "quiet luxury", "old money aesthetic", "mob wife aesthetic", "clean girl aesthetic", "coastal grandmother",
    "capsule wardrobe", "minimalist wardrobe", "outfit of the day", "ootd", "grwm outfit",
    "amazon fashion finds", "amazon must haves", "shein haul", "temu haul", "thrift haul",
    "vintage finds", "designer dupe", "luxury dupe", "it girl style", "street style",
    "coquette aesthetic", "ballet core", "office siren", "tenniscore", "blokecore",
    "dark academia", "light academia", "cottagecore outfit", "y2k fashion", "90s style",
    "matching set", "co-ord set", "linen pants", "wide leg jeans", "barrel jeans",
    "platform sneakers", "chunky loafers", "ballet flats", "kitten heels", "knee high boots",
    "crossbody bag", "tote bag", "belt bag", "cloud bag", "shoulder bag",
    "gold jewelry", "layered necklaces", "hoop earrings", "pearl accessories", "hair claw clip",
    "silk scarf", "baseball cap outfit", "sunglasses trend", "oversized blazer", "leather jacket"
  ],
  "Tech / Gadgets": [
    "apple", "samsung", "google pixel", "oneplus", "nothing phone",
    "airpods", "airpods pro", "airpods max", "sony wh-1000xm5", "bose quietcomfort",
    "iphone", "iphone case", "magsafe", "ipad", "ipad pro",
    "macbook", "macbook air", "macbook pro", "imac", "mac mini",
    "apple watch", "apple watch ultra", "samsung galaxy watch", "garmin watch", "fitbit",
    "meta quest", "vision pro", "playstation", "nintendo switch", "steam deck",
    "mechanical keyboard", "custom keyboard", "keychron", "desk setup", "desk mat",
    "monitor arm", "standing desk", "ergonomic chair", "webcam", "ring light",
    "portable charger", "wireless charger", "usb c hub", "cable organizer", "tech organizer",
    "smart home", "alexa", "google home", "smart plug", "smart light",
    "robot vacuum", "roomba", "roborock", "dyson vacuum", "cordless vacuum",
    "dyson airwrap", "dyson supersonic", "hair dryer", "flat iron", "curling iron",
    "projector", "mini projector", "portable speaker", "bluetooth speaker", "jbl speaker",
    "action camera", "gopro", "dji", "drone", "gimbal",
    "kindle", "e-reader", "tablet stand", "laptop stand", "phone mount",
    "airtag", "tile tracker", "smart lock", "video doorbell", "security camera",
    "3d printer", "raspberry pi", "arduino", "soldering kit", "electronics kit",
    "gaming mouse", "gaming headset", "gaming monitor", "rgb lighting", "pc build"
  ],
  "Food / Beverage": [
    "starbucks", "dunkin", "trader joe's", "whole foods", "costco finds",
    "chipotle", "chick-fil-a", "mcdonald's", "in-n-out", "raising cane's",
    "celsius", "prime hydration", "liquid iv", "poppi", "olipop",
    "protein coffee", "protein shake", "fairlife protein", "premier protein", "ghost energy",
    "stanley cup", "yeti tumbler", "hydroflask", "water bottle", "ice cup",
    "air fryer recipe", "air fryer hack", "instant pot", "ninja creami", "solo stove",
    "meal prep", "meal prep ideas", "high protein meals", "macro friendly", "calorie deficit",
    "cottage cheese recipe", "cottage cheese ice cream", "greek yogurt bark", "protein pancakes", "overnight oats",
    "baked oats", "banana bread", "sourdough bread", "focaccia art", "pasta recipe",
    "butter board", "charcuterie board", "grazing table", "snack board", "lunchbox ideas",
    "matcha latte", "chai latte", "dirty chai", "iced coffee recipe", "cold brew",
    "smoothie recipe", "green smoothie", "acai bowl", "protein bowl", "poke bowl",
    "crumbl cookies", "nothing bundt cakes", "boba tea", "bubble tea", "mochi",
    "korean corn dog", "birria tacos", "hot honey", "everything bagel seasoning", "chili crunch",
    "pickled onions", "fermented foods", "kimchi", "kombucha", "gut health drink",
    "kitchen gadgets", "kitchen organization", "pantry organization", "fridge organization", "spice rack",
    "grocery haul", "costco haul", "aldi finds", "target grocery", "walmart finds"
  ],
  "Fitness / Wellness": [
    "peloton", "mirror workout", "tonal", "planet fitness", "orangetheory",
    "crossfit", "f45 training", "barry's bootcamp", "soulcycle", "club pilates",
    "creatine", "pre workout", "protein powder", "bcaa", "electrolytes",
    "walking pad", "under desk treadmill", "mini stepper", "resistance bands", "booty bands",
    "cold plunge", "ice bath", "sauna blanket", "red light therapy", "infrared sauna",
    "foam roller", "massage gun", "theragun", "stretching routine", "mobility work",
    "pilates", "yoga flow", "hot yoga", "barre workout", "reformer pilates",
    "12-3-30 workout", "75 hard", "cozy cardio", "hot girl walk", "morning workout",
    "weightlifting", "deadlift form", "squat form", "bench press", "glute bridge",
    "home gym", "garage gym", "gym bag essentials", "gym outfit", "workout shoes",
    "running shoes", "marathon training", "couch to 5k", "half marathon", "trail running",
    "jump rope", "battle ropes", "kettlebell workout", "dumbbell workout", "bodyweight workout",
    "yoga mat", "yoga block", "workout leggings", "sports bra", "gym shark",
    "wrist wraps", "lifting belt", "knee sleeves", "pull up bar", "dip station",
    "fitness tracker", "whoop band", "oura ring", "apple watch fitness", "heart rate monitor",
    "sleep optimization", "sleep hygiene", "mouth taping", "magnesium sleep", "melatonin"
  ],
  "Home / Decor": [
    "led strip lights", "sunset lamp", "mushroom lamp", "cloud light", "neon sign",
    "cloud couch", "nugget couch", "modular sofa", "accent chair", "papasan chair",
    "floating shelves", "bookshelf styling", "gallery wall", "picture ledge", "wall art",
    "peel and stick wallpaper", "accent wall", "board and batten", "wainscoting", "shiplap",
    "stanley cup organizer", "tumbler organizer", "kitchen organizer", "drawer organizer", "closet organizer",
    "amazon home finds", "amazon home decor", "target home finds", "ikea hack", "diy home decor",
    "bathroom organization", "shower caddy", "towel rack", "bathroom shelf", "vanity mirror",
    "bedding set", "linen sheets", "duvet cover", "throw pillows", "weighted blanket",
    "candle", "yankee candle", "bath and body works", "diffuser", "essential oils",
    "indoor plants", "plant care", "pothos", "monstera", "fiddle leaf fig",
    "plant shelf", "planter pot", "self watering planter", "propagation station", "terrarium",
    "rug", "area rug", "washable rug", "ruggable", "doormat",
    "curtain rod", "blackout curtains", "linen curtains", "shower curtain", "window treatment",
    "kitchen faucet", "cabinet hardware", "drawer pulls", "light fixture", "ceiling fan",
    "smart thermostat", "nest thermostat", "ring doorbell", "smart blinds", "robot mop",
    "laundry room", "laundry organization", "cleaning products", "cleaning hack", "deep clean"
  ],
  "Finance / Investing": [
    "robinhood", "webull", "fidelity", "charles schwab", "td ameritrade",
    "coinbase", "crypto.com", "binance", "metamask", "phantom wallet",
    "sofi", "chime", "marcus", "ally bank", "discover savings",
    "dividend stocks", "dividend investing", "passive income", "compound interest", "index funds",
    "s&p 500", "voo", "vti", "qqq", "spy",
    "roth ira", "401k", "hsa investing", "retirement planning", "fire movement",
    "bitcoin", "ethereum", "solana", "crypto", "nft",
    "stock market", "stock picks", "growth stocks", "value investing", "options trading",
    "real estate investing", "rental property", "house hacking", "airbnb investing", "reit",
    "budgeting", "budget hack", "sinking fund", "cash stuffing", "envelope system",
    "credit card points", "travel hacking", "credit score", "credit building", "debt payoff",
    "side hustle", "freelancing", "etsy shop", "dropshipping", "amazon fba",
    "personal finance", "money saving tips", "frugal living", "financial freedom", "net worth",
    "tax tips", "tax refund", "tax bracket", "capital gains", "tax loss harvesting",
    "high yield savings", "money market", "cd rates", "i bonds", "treasury bonds"
  ],
  "Travel": [
    "packing cubes", "carry on only", "travel backpack", "weekender bag", "packing hack",
    "airport hack", "airport outfit", "tsa precheck", "global entry", "clear membership",
    "hotel hack", "hotel points", "marriott bonvoy", "hilton honors", "hyatt points",
    "airline miles", "delta skymiles", "united mileageplus", "southwest points", "flight deal",
    "airbnb", "vrbo", "hostel", "boutique hotel", "resort review",
    "travel essentials", "carry on essentials", "toiletry bag", "travel pillow", "neck pillow",
    "noise cancelling headphones", "travel adapter", "portable wifi", "travel journal", "travel camera",
    "europe trip", "japan travel", "bali travel", "thailand travel", "mexico travel",
    "road trip", "national parks", "camping gear", "glamping", "van life",
    "cruise review", "disney cruise", "royal caribbean", "norwegian cruise", "cruise tips",
    "travel outfit", "airplane outfit", "resort wear", "beach outfit", "hiking outfit",
    "passport holder", "luggage tag", "suitcase review", "away luggage", "samsonite",
    "travel skincare", "travel makeup", "mini toiletries", "solid shampoo", "travel containers",
    "solo travel", "girls trip", "couples trip", "family vacation", "budget travel"
  ],
  "Entertainment": [
    "netflix", "hulu", "disney plus", "hbo max", "amazon prime video",
    "apple tv plus", "peacock", "paramount plus", "youtube premium", "crunchyroll",
    "spotify", "apple music", "tidal", "vinyl records", "record player",
    "booktok", "book recommendation", "kindle unlimited", "audiobook", "book club",
    "romance books", "fantasy books", "thriller books", "self help books", "manga",
    "gaming setup", "ps5", "xbox series x", "nintendo switch oled", "gaming pc",
    "fortnite", "call of duty", "zelda", "mario", "pokemon",
    "taylor swift", "beyonce", "concert outfit", "concert essentials", "festival outfit",
    "coachella", "music festival", "eras tour", "kpop", "bts",
    "true crime podcast", "comedy podcast", "wellness podcast", "business podcast", "podcast setup",
    "board games", "card games", "puzzle", "lego set", "diamond painting",
    "movie review", "tv show review", "binge watch", "watch list", "movie night",
    "tiktok trend", "instagram reels", "youtube shorts", "content creator", "influencer",
    "streaming setup", "microphone", "camera for youtube", "editing software", "thumbnail design"
  ],
  "Health / Supplements": [
    "magnesium", "magnesium glycinate", "magnesium threonate", "zinc", "vitamin d",
    "vitamin b12", "iron supplement", "omega 3", "fish oil", "cod liver oil",
    "ashwagandha", "rhodiola", "lions mane", "reishi mushroom", "cordyceps",
    "probiotics", "prebiotics", "digestive enzymes", "gut health", "leaky gut",
    "collagen powder", "collagen peptides", "biotin", "keratin supplement", "hair vitamins",
    "turmeric", "curcumin", "ginger supplement", "elderberry", "echinacea",
    "melatonin", "valerian root", "l-theanine", "gaba supplement", "sleep supplement",
    "adderall alternative", "focus supplement", "nootropics", "brain fog", "cognitive health",
    "greens powder", "ag1 athletic greens", "super greens", "spirulina", "chlorella",
    "berberine", "glucose goddess", "blood sugar hack", "cgm monitor", "metabolic health",
    "seed probiotic", "ritual vitamins", "care/of vitamins", "persona vitamins", "prenatal vitamins",
    "morning routine supplement", "supplement stack", "supplement organizer", "pill organizer", "vitamin routine",
    "apple cider vinegar", "acv gummies", "fiber supplement", "psyllium husk", "flaxseed",
    "electrolyte powder", "lmnt", "liquid iv", "nuun tablets", "coconut water",
    "adaptogens", "maca root", "holy basil", "tongkat ali", "fadogia agrestis"
  ],
  "Baby / Parenting": [
    "snoo", "hatch sound machine", "owlet monitor", "nanit camera", "baby monitor",
    "uppababy stroller", "doona stroller", "baby bjorn carrier", "ergobaby", "baby wrap",
    "baby registry", "baby must haves", "newborn essentials", "hospital bag", "postpartum essentials",
    "baby clothes", "baby outfit", "baby shoes", "baby headband", "baby swimsuit",
    "baby food maker", "baby led weaning", "puree recipe", "toddler meals", "picky eater tips",
    "baby bottle", "dr brown bottles", "bottle warmer", "breast pump", "hakaa pump",
    "diaper bag", "diaper caddy", "wipe warmer", "changing pad", "diaper cream",
    "baby bath", "baby shampoo", "baby lotion", "baby sunscreen", "baby laundry detergent",
    "nursery decor", "crib bedding", "nursery organization", "baby closet", "nursery rug",
    "toddler hack", "toddler activity", "sensory play", "busy board", "montessori toys",
    "baby toy", "teething toy", "play mat", "baby gym", "jumperoo",
    "car seat", "convertible car seat", "car seat cover", "stroller organizer", "travel stroller",
    "baby gate", "outlet covers", "cabinet locks", "baby proofing", "corner protectors",
    "potty training", "toddler bed", "sleep training", "bedtime routine", "white noise machine"
  ],
  "Pet": [
    "farmer's dog", "ollie dog food", "chewy", "barkbox", "kong toys",
    "pet camera", "furbo", "automatic feeder", "pet water fountain", "slow feeder bowl",
    "dog enrichment", "snuffle mat", "lick mat", "puzzle feeder", "treat dispenser",
    "dog crate", "dog bed", "calming bed", "orthopedic dog bed", "elevated dog bed",
    "dog harness", "no pull harness", "retractable leash", "dog collar", "airtag dog collar",
    "cat tree", "cat tower", "cat scratcher", "cat bed", "cat hammock",
    "automatic litter box", "litter robot", "cat litter", "litter mat", "litter deodorizer",
    "dog grooming", "pet shampoo", "deshedding tool", "nail grinder", "ear cleaner",
    "dog training", "puppy training", "clicker training", "dog treats", "training treats",
    "dog dental chew", "greenies", "yak chew", "bully stick", "antler chew",
    "pet insurance", "trupanion", "lemonade pet", "healthy paws", "petplan",
    "dog jacket", "dog raincoat", "dog boots", "dog sweater", "cooling vest",
    "fish tank", "aquarium", "reptile terrarium", "hamster cage", "bird cage",
    "pet stroller", "dog carrier", "cat carrier", "pet travel", "dog car seat"
  ],
  "Signal Phrases": [
    "restock alert", "back in stock", "run don't walk", "sold out everywhere",
    "tiktok made me buy", "tiktok viral", "tiktok famous", "trending on tiktok",
    "amazon must haves", "amazon finds", "amazon haul", "amazon favorites",
    "dupe alert", "dupe for", "budget friendly", "affordable alternative",
    "holy grail", "game changer", "life changing", "obsessed with",
    "limited edition", "limited drop", "new launch", "just dropped",
    "honest review", "full review", "worth the hype", "overhyped",
    "before and after", "transformation", "glow up", "level up",
    "money saving", "save your money", "don't waste money", "worth every penny",
    "underrated", "hidden gem", "best kept secret", "slept on",
    "side by side comparison", "vs comparison", "which is better", "battle of",
    "unboxing", "first impression", "try on haul", "get ready with me",
    "day in my life", "weekly reset", "sunday reset", "that girl routine",
    "aesthetic", "satisfying", "oddly satisfying", "asmr",
    "pov", "storytime", "greenscreen", "duet this",
    "target finds", "target run", "target haul", "walmart finds",
    "costco finds", "costco haul", "dollar tree finds", "tj maxx finds",
    "five below finds", "marshalls finds", "homegoods finds", "ross finds"
  ]
};

export function getKeywordLibraryStats(): { category: string; count: number }[] {
  return Object.entries(KEYWORD_LIBRARY).map(([category, keywords]) => ({
    category,
    count: keywords.length,
  }));
}

export function getAllKeywordsFromCategories(categories: string[]): string[] {
  return categories.flatMap((cat) => KEYWORD_LIBRARY[cat] || []);
}

export function getTotalKeywordCount(): number {
  return Object.values(KEYWORD_LIBRARY).reduce((sum, arr) => sum + arr.length, 0);
}
