// Brand-to-ticker cache for fast lookups (fallback before AI mapping)
const BRANDS = [
  { name: "Stanley", companies: [{ company: "Stanley Black & Decker", ticker: "SWK", exchange: "NYSE" }] },
  { name: "CeraVe", companies: [{ company: "L'Oréal", ticker: "OR.PA", exchange: "Euronext" }] },
  { name: "Dyson", companies: [] },
  { name: "Starbucks", companies: [{ company: "Starbucks Corporation", ticker: "SBUX", exchange: "NASDAQ" }] },
  { name: "Crocs", companies: [{ company: "Crocs, Inc.", ticker: "CROX", exchange: "NASDAQ" }] },
  { name: "Lululemon", companies: [{ company: "Lululemon Athletica", ticker: "LULU", exchange: "NASDAQ" }] },
  { name: "Drunk Elephant", companies: [{ company: "Shiseido", ticker: "4911.T", exchange: "TSE" }] },
  { name: "Sol de Janeiro", companies: [] },
  { name: "Rare Beauty", companies: [] },
  { name: "Olaplex", companies: [{ company: "Olaplex Holdings", ticker: "OLPX", exchange: "NASDAQ" }] },
  { name: "e.l.f. Cosmetics", companies: [{ company: "e.l.f. Beauty", ticker: "ELF", exchange: "NYSE" }] },
  { name: "Nike", companies: [{ company: "Nike, Inc.", ticker: "NKE", exchange: "NYSE" }] },
  { name: "Apple", companies: [{ company: "Apple Inc.", ticker: "AAPL", exchange: "NASDAQ" }] },
  { name: "Glossier", companies: [] },
  { name: "Rhode Skin", companies: [] },
  { name: "Skims", companies: [] },
  { name: "Ugg", companies: [{ company: "Deckers Outdoor", ticker: "DECK", exchange: "NYSE" }] },
  { name: "Trader Joe's", companies: [] },
  { name: "Alo Yoga", companies: [] },
  { name: "Beis Travel", companies: [] },
  { name: "Samsung", companies: [{ company: "Samsung Electronics", ticker: "005930.KS", exchange: "KRX" }] },
  { name: "Sony", companies: [{ company: "Sony Group", ticker: "SONY", exchange: "NYSE" }] },
  { name: "Google", companies: [{ company: "Alphabet Inc.", ticker: "GOOGL", exchange: "NASDAQ" }] },
  { name: "Meta", companies: [{ company: "Meta Platforms", ticker: "META", exchange: "NASDAQ" }] },
  { name: "Amazon", companies: [{ company: "Amazon.com", ticker: "AMZN", exchange: "NASDAQ" }] },
  { name: "Microsoft", companies: [{ company: "Microsoft Corp.", ticker: "MSFT", exchange: "NASDAQ" }] },
  { name: "Tesla", companies: [{ company: "Tesla, Inc.", ticker: "TSLA", exchange: "NASDAQ" }] },
  { name: "Nvidia", companies: [{ company: "NVIDIA Corp.", ticker: "NVDA", exchange: "NASDAQ" }] },
  { name: "AMD", companies: [{ company: "Advanced Micro Devices", ticker: "AMD", exchange: "NASDAQ" }] },
  { name: "Intel", companies: [{ company: "Intel Corp.", ticker: "INTC", exchange: "NASDAQ" }] },
  { name: "Spotify", companies: [{ company: "Spotify Technology", ticker: "SPOT", exchange: "NYSE" }] },
  { name: "Netflix", companies: [{ company: "Netflix, Inc.", ticker: "NFLX", exchange: "NASDAQ" }] },
  { name: "Disney", companies: [{ company: "Walt Disney Co.", ticker: "DIS", exchange: "NYSE" }] },
  { name: "Roku", companies: [{ company: "Roku, Inc.", ticker: "ROKU", exchange: "NASDAQ" }] },
  { name: "Adidas", companies: [{ company: "Adidas AG", ticker: "ADS.DE", exchange: "XETRA" }] },
  { name: "Under Armour", companies: [{ company: "Under Armour", ticker: "UAA", exchange: "NYSE" }] },
  { name: "Gap", companies: [{ company: "Gap, Inc.", ticker: "GAP", exchange: "NYSE" }] },
  { name: "Ralph Lauren", companies: [{ company: "Ralph Lauren Corp.", ticker: "RL", exchange: "NYSE" }] },
  { name: "Tapestry", companies: [{ company: "Tapestry, Inc.", ticker: "TPR", exchange: "NYSE" }] },
  { name: "Capri Holdings", companies: [{ company: "Capri Holdings", ticker: "CPRI", exchange: "NYSE" }] },
  { name: "VF Corporation", companies: [{ company: "VF Corporation", ticker: "VFC", exchange: "NYSE" }] },
  { name: "Hanesbrands", companies: [{ company: "Hanesbrands", ticker: "HBI", exchange: "NYSE" }] },
  { name: "Abercrombie", companies: [{ company: "Abercrombie & Fitch", ticker: "ANF", exchange: "NYSE" }] },
  { name: "New Balance", companies: [] },
  { name: "On Running", companies: [{ company: "On Holding AG", ticker: "ONON", exchange: "NYSE" }] },
  { name: "Hoka", companies: [{ company: "Deckers Outdoor", ticker: "DECK", exchange: "NYSE" }] },
  { name: "Birkenstock", companies: [{ company: "Birkenstock Holding", ticker: "BIRK", exchange: "NYSE" }] },
  { name: "Coca-Cola", companies: [{ company: "Coca-Cola Co.", ticker: "KO", exchange: "NYSE" }] },
  { name: "PepsiCo", companies: [{ company: "PepsiCo, Inc.", ticker: "PEP", exchange: "NASDAQ" }] },
  { name: "Chipotle", companies: [{ company: "Chipotle Mexican Grill", ticker: "CMG", exchange: "NYSE" }] },
  { name: "McDonald's", companies: [{ company: "McDonald's Corp.", ticker: "MCD", exchange: "NYSE" }] },
  { name: "Celsius", companies: [{ company: "Celsius Holdings", ticker: "CELH", exchange: "NASDAQ" }] },
  { name: "Monster Beverage", companies: [{ company: "Monster Beverage", ticker: "MNST", exchange: "NASDAQ" }] },
  { name: "Hershey", companies: [{ company: "Hershey Co.", ticker: "HSY", exchange: "NYSE" }] },
  { name: "Mondelez", companies: [{ company: "Mondelez International", ticker: "MDLZ", exchange: "NASDAQ" }] },
  { name: "General Mills", companies: [{ company: "General Mills", ticker: "GIS", exchange: "NYSE" }] },
  { name: "Keurig Dr Pepper", companies: [{ company: "Keurig Dr Pepper", ticker: "KDP", exchange: "NASDAQ" }] },
  { name: "Sweetgreen", companies: [{ company: "Sweetgreen, Inc.", ticker: "SG", exchange: "NYSE" }] },
  { name: "Dutch Bros", companies: [{ company: "Dutch Bros Inc.", ticker: "BROS", exchange: "NYSE" }] },
  { name: "Peloton", companies: [{ company: "Peloton Interactive", ticker: "PTON", exchange: "NASDAQ" }] },
  { name: "Planet Fitness", companies: [{ company: "Planet Fitness", ticker: "PLNT", exchange: "NYSE" }] },
  { name: "Garmin", companies: [{ company: "Garmin Ltd.", ticker: "GRMN", exchange: "NYSE" }] },
  { name: "Fitbit", companies: [{ company: "Alphabet Inc.", ticker: "GOOGL", exchange: "NASDAQ" }] },
  { name: "Whoop", companies: [] },
  { name: "Gymshark", companies: [] },
  { name: "Wayfair", companies: [{ company: "Wayfair Inc.", ticker: "W", exchange: "NYSE" }] },
  { name: "Restoration Hardware", companies: [{ company: "RH", ticker: "RH", exchange: "NYSE" }] },
  { name: "Williams-Sonoma", companies: [{ company: "Williams-Sonoma", ticker: "WSM", exchange: "NYSE" }] },
  { name: "Ethan Allen", companies: [{ company: "Ethan Allen Interiors", ticker: "ETD", exchange: "NYSE" }] },
  { name: "Bed Bath & Beyond", companies: [] },
  { name: "IKEA", companies: [] },
  { name: "Target", companies: [{ company: "Target Corp.", ticker: "TGT", exchange: "NYSE" }] },
  { name: "Walmart", companies: [{ company: "Walmart Inc.", ticker: "WMT", exchange: "NYSE" }] },
  { name: "Costco", companies: [{ company: "Costco Wholesale", ticker: "COST", exchange: "NASDAQ" }] },
  { name: "Robinhood", companies: [{ company: "Robinhood Markets", ticker: "HOOD", exchange: "NASDAQ" }] },
  { name: "Coinbase", companies: [{ company: "Coinbase Global", ticker: "COIN", exchange: "NASDAQ" }] },
  { name: "SoFi", companies: [{ company: "SoFi Technologies", ticker: "SOFI", exchange: "NASDAQ" }] },
  { name: "PayPal", companies: [{ company: "PayPal Holdings", ticker: "PYPL", exchange: "NASDAQ" }] },
  { name: "Block", companies: [{ company: "Block, Inc.", ticker: "XYZ", exchange: "NYSE" }] },
  { name: "Affirm", companies: [{ company: "Affirm Holdings", ticker: "AFRM", exchange: "NASDAQ" }] },
  { name: "Hims & Hers", companies: [{ company: "Hims & Hers Health", ticker: "HIMS", exchange: "NYSE" }] },
  { name: "GNC", companies: [] },
  { name: "Vital Proteins", companies: [{ company: "Nestlé", ticker: "NSRGY", exchange: "OTC" }] },
  { name: "Airbnb", companies: [{ company: "Airbnb, Inc.", ticker: "ABNB", exchange: "NASDAQ" }] },
  { name: "Booking.com", companies: [{ company: "Booking Holdings", ticker: "BKNG", exchange: "NASDAQ" }] },
  { name: "Expedia", companies: [{ company: "Expedia Group", ticker: "EXPE", exchange: "NASDAQ" }] },
  { name: "Marriott", companies: [{ company: "Marriott International", ticker: "MAR", exchange: "NASDAQ" }] },
  { name: "Hilton", companies: [{ company: "Hilton Worldwide", ticker: "HLT", exchange: "NYSE" }] },
  { name: "Chewy", companies: [{ company: "Chewy, Inc.", ticker: "CHWY", exchange: "NYSE" }] },
  { name: "Petco", companies: [{ company: "Petco Health", ticker: "WOOF", exchange: "NASDAQ" }] },
  { name: "Freshpet", companies: [{ company: "Freshpet, Inc.", ticker: "FRPT", exchange: "NASDAQ" }] },
  { name: "Roblox", companies: [{ company: "Roblox Corp.", ticker: "RBLX", exchange: "NYSE" }] },
  { name: "Electronic Arts", companies: [{ company: "Electronic Arts", ticker: "EA", exchange: "NASDAQ" }] },
  { name: "Take-Two", companies: [{ company: "Take-Two Interactive", ticker: "TTWO", exchange: "NASDAQ" }] },
  { name: "Warner Bros", companies: [{ company: "Warner Bros. Discovery", ticker: "WBD", exchange: "NASDAQ" }] },
];

/** Fast cache lookup for known brand-to-ticker mappings */
export function getCachedBrandMatch(brandName: string) {
  const brand = BRANDS.find(
    (b) => b.name.toLowerCase() === brandName.toLowerCase()
  );
  return brand?.companies?.[0] || null;
}

export { BRANDS };
